### ISSUE TITLE
BCM wrong colony data

### ISSUE THREAD

**Issue by albags** [mpi2/impc-production-tracker#1009]
error, STAMB as the phenotyping colony ID at GenTaR for the Slc2a10 line.  This is incorrect (it should be STCGB, as in the table below); I presume it arose during what would have been a batch assignment for entering colony information back when we had people working from home last year (imaging that it was a copy and paste issue from what was a big spreadsheet of lines).

BCM.2021-06-15.10.impc.zip
Gene         Production colony     Phenotyping colony
Slc2a10     STTA                          STCG
<-- needs correction at GenTaR is presently STAMB!

Strada       STAA                          STAM
<-- needs to be entered to GenTaR

**Comment by rwilson-ebi** [comment]
Updated GenTaR so you cannot change the privacy of a project once the project has a phenotyping plan in the Phenotyping Started state, and asked the wranglers to modify this project so BCM can change the colony name.
