### ISSUE TITLE
Add Outcome Restriction

### ISSUE THREAD

**Issue by ogunes-ebi** [mpi2/impc-production-tracker#1158]

**Comment by ogunes-ebi** [comment]
rule 1 : *ngIf="outcomes?.length === 1 && (attemptType === 'es cell allele modification' || attemptType === 'es cell')
rule 2: if plan is in abborted state
rule 2 : Cre Excision Complete allow for ecm
Founders Obtained(crspr)
Embryos Obtained(He Crspr)
Chimeras/Founders Obtained (Es cell)

**Comment by rwilson-ebi** [comment]
Create a new endpoint for validation in the front-end validation
