### ISSUE TITLE
Validate if we can use jwt spring library in the project

### ISSUE THREAD

**Issue by mauroz77** [mpi2/impc-production-tracker#2]
Validate if we can use the spring library org.springframework.security.spring-security-jwt instead using io.jsonwebtoken.jjwt for the JWT handling logic.

**Comment by mauroz77** [comment]
Regarding this, I've checked several examples for JWT in java with spring, and most of the times I've seen them using one of these two jwt libraries:

https://github.com/jwtk/jjwt (the one we are using)
https://github.com/auth0/java-jwt

The documentation is good, there are lots of articles in internet explaining how to use them and the projects in github seem to be pretty active. The APIs they provided are fluent, and intuitive to use. Classes in org.springframework.security.spring-security-jwt on the other hand, seem to be less intuitive to use, and we may end up writing some classes that the other libraries already provide. Any thoughts @jmason-ebi @albags @rwilson-ebi ?

**Comment by jmason-ebi** [comment]
Thanks for checking in to this.  Would be nice to use the spring dependency management, but looks like neither of these are included [1]. 

I defer to you – use what’s best, but keeping in mind that it’s better in general to leverage the spring dependency management when possible to avoid incompatible versions of libraries.

 

[1] - https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html

**Comment by mauroz77** [comment]
Closing because of the reasons in the comments. Taking into account the use of spring dependency management whenever possible.
